// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig} from "prisma/config";
import path from "node:path";

export default defineConfig({
  schema: "prisma/schema.prisma",

  migrations: {
    path: path.join("prisma", "migrations"),
  }
});
